# Generated by Django 4.2 on 2023-04-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_useraddress_userpayment_rename_orderltem_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
