# Generated by Django 4.2 on 2023-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_address_useraddress_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='district',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
