# Generated by Django 4.2 on 2023-04-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_productcategory_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
