# Generated by Django 4.2 on 2023-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
