# Generated by Django 4.2 on 2023-05-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_useraddress_city_product_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='useStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
