# Generated by Django 4.2 on 2023-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_product_description_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bidStatus',
            field=models.CharField(default='Passive', max_length=10),
        ),
    ]
