# Generated by Django 4.2 on 2023-05-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_product_bidstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bidStatus',
        ),
    ]
