# Generated by Django 4.2 on 2023-05-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_product_bidstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currentHighestBid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='totalBids',
        ),
    ]
