# Generated by Django 4.2 on 2023-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_product_currenthighestbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currentHighestBid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='totalBids',
            field=models.IntegerField(default=0),
        ),
    ]
