# Generated by Django 4.2 on 2023-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_product_currenthighestbid_product_totalbids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
