# Generated by Django 4.2 on 2023-05-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_bid_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='paidAmount',
            field=models.IntegerField(default=0),
        ),
    ]
