# Generated by Django 4.2 on 2023-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_bid_paidamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ending_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
