# Generated by Django 4.2 on 2023-05-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_bid_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videoURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
