# Generated by Django 4.2 on 2023-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_product_videourl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ending_email_sent',
            new_name='endingEmailSent',
        ),
        migrations.AddField(
            model_name='product',
            name='winnerEmailSent',
            field=models.BooleanField(default=False),
        ),
    ]
