# Generated by Django 4.2 on 2023-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_rename_ending_email_sent_product_endingemailsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Modified'), (3, 'Passive')], default=1),
        ),
    ]
