# Generated by Django 4.2 on 2023-06-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_rename_winneremailsent_product_lastemailsent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paidAt',
            new_name='confirmedAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='isConfirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentMethod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
