# Generated by Django 4.2 on 2023-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_order_address_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
