# Generated by Django 4.2 on 2023-06-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_order_onshipping_order_shippingat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='onShipping',
            new_name='inShipping',
        ),
    ]
