# Generated by Django 4.2 on 2023-06-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_onshipping_order_inshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingCode',
            field=models.CharField(blank=True, null=True),
        ),
    ]
